# name: semantic-pull-request
# on:
#   # - a PR is opened, labeled or a commit is pushed (synchronize)
#   pull_request:
#     types: [opened, reopened, edited, ready_for_review, labeled, synchronize]

# jobs:
#   action-semantic-pull-request:
#     name: action-semantic-pull-request
#     runs-on: ubuntu-latest
#     steps:
#       - name: Validate PR title
#         uses: amannn/action-semantic-pull-request@v5
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#         with:
#           # Configure which types are allowed
#           # Default: https://github.com/commitizen/conventional-commit-types
#           types: |
#             fix
#             feat
#             docs
#             ci
#             chore
#             refactor
#             revert
#             test
#           # Configure that a scope must always be provided.
#           requireScope: false
#           # For work-in-progress PRs you can typically use draft pull requests
#           # from Github. However, private repositories on the free plan don't have
#           # this option and therefore this action allows you to opt-in to using the
#           # special "[WIP]" prefix to indicate this state. This will avoid the
#           # validation of the PR title and the pull request checks remain pending.
#           # Note that a second check will be reported if this is enabled.
#           wip: true